### ISSUE TITLE
Minor typo FILE vs File

### ISSUE THREAD

**Issue by cgpu** [PGP-UK/GenomeChronicler#1]
`FILE`: https://github.com/PGP-UK/GenomeChronicler/blob/a3a92697cc5549d4f649dc615c740eb75c5f9ef6/GenomeChronicler_mainDruid.pl#L157

`File`: https://github.com/PGP-UK/GenomeChronicler/blob/a3a92697cc5549d4f649dc615c740eb75c5f9ef6/GenomeChronicler_mainDruid.pl#L168

**Comment by afonsoguerra** [comment]
Thanks for spotting that. Just fixed.
