### ISSUE TITLE
Update repo in git clone command (Singularity) to fetch from PGP-UK

### ISSUE THREAD

**Issue by cgpu** [PGP-UK/GenomeChronicler#2]
From this:

https://github.com/PGP-UK/GenomeChronicler/blob/a3a92697cc5549d4f649dc615c740eb75c5f9ef6/Singularity#L74

To that:

`https://github.com/PGP-UK/GenomeChronicler.git`

**Comment by afonsoguerra** [comment]
I am aware of this one, and the respective path changes in the recipe due to repo name change, but I am having trouble connecting singularity hub to the PGP org.

**Comment by cgpu** [comment]
I see, that's ok. For the docker images I created one tagged `dev` and one `pgp-uk` , each git clones for the respective repo. Feel free to close issue.

**Comment by afonsoguerra** [comment]
Great, thanks!
