### ISSUE TITLE
Possible cause of issue - cannot find .pl files for completing steps before report

### ISSUE THREAD

**Issue by cgpu** [PGP-UK/GenomeChronicler#3]
Check this line:

https://github.com/PGP-UK/GenomeChronicler/blob/a3a92697cc5549d4f649dc615c740eb75c5f9ef6/scripts/GenomeChronicler_ancestry_generator_fromBAM.pl#L17

I think this causes the problem and the `script/*.pl` cannot be found and as a result the final report cannot be created. 

I am cloning this (PGP-UK) repo, and the errors are:

![image](https://user-images.githubusercontent.com/38183826/66949326-393e2480-f04e-11e9-9175-5c86ea5cf2f1.png)

- `Can't open perl script "scripts/GenomeChronicler_vepTables_fromVEP.pl": No such file or directory` 
> check if this needs to be the full path eg. `/GenomeChronicler/scripts/GenomeChronicler_vepTables_fromVEP.pl`
 
- `Can't exec "/GenomeChroniclerDev//software/samtools": No such file or directory at /GenomeChronicler/genomechronicler line 373.`
> check if this needs to be changed into the PGP repo name eg. `/GenomeChronicler/scripts/GenomeChronicler_vepTables_fromVEP.pl`

**Comment by afonsoguerra** [comment]
The second one is definitely correct, path needs changing to remove the Dev (but that will invariably break the other repo). The first one is a bit more puzzling. Where are you running the main pl from? 
I've pushed some changes to try and address that, like you suggest. Give it a try and let me know if it helps. More precisely, I've changed the path of $dir to remove the Dev and added a ${dir} variable before the script names to make the path absolute.

**Comment by cgpu** [comment]
Thanks Afonso - I did the same in my fork to be able to build the Docker and test.

> Where are you running the main pl from?
 
I am using the `genomechronicler` symlink. This is in `/GenomeChronicler{' ', 'Dev' }/genomechronicler. `

I'll ping you tomorrow once I test with the updated Docker image :whale:

**Comment by afonsoguerra** [comment]
Hopefully the latest commits will fix the majority of the issues; let's discuss soon to iron out the final bugs.
