### ISSUE TITLE
R script cannot access "results/results_",.. file

### ISSUE THREAD

**Issue by cgpu** [PGP-UK/GenomeChronicler#4]
Rebuilt the container after your last push. No compaints about GenomeChronicler related paths which is cool.

Now I am getting an error from the R script - it cannot access the `eigenvec` file.
It complains about this line:

https://github.com/PGP-UK/GenomeChronicler/blob/212d189e4daa129792b3588b9466c43e88eb28ed/scripts/GenomeChronicler_plot_generator_fromAncestry.R#L7

Where is this file first generated?
Fix no 1 could to give absolut path for this file.

Can you try this as a first fix?

Else we could follow the R style with here::here() to set relative paths from the scripts current dir, but let's hope as a first iteration the absolut path will do.

**Comment by cgpu** [comment]
Still having the same error message.

Some parts that still have `results/` relative path to check:

## Currently commented out: 
>
- [X] https://github.com/PGP-UK/GenomeChronicler/blob/212d189e4daa129792b3588b9466c43e88eb28ed/scripts/GenomeChronicler_genoTables_fromAfoGeno.pl#L44

- [X] https://github.com/PGP-UK/GenomeChronicler/blob/bf7301fdf923bb339285a21c76e224f31586be4a/GenomeChronicler_mainDruid.pl#L88

## These will run: 

- [ ] https://github.com/PGP-UK/GenomeChronicler/blob/bf7301fdf923bb339285a21c76e224f31586be4a/GenomeChronicler_mainDruid.pl#L226

- [ ] https://github.com/PGP-UK/GenomeChronicler/blob/bf7301fdf923bb339285a21c76e224f31586be4a/GenomeChronicler_mainDruid.pl#L281

I'll check in my fork for now and will ping you again.

**Comment by cgpu** [comment]
Update:

This update addresses the leftover non-absolut paths after your latest push.
👉 https://github.com/cgpu/GenomeChronicler/commit/76cb74cb54f643cb68ece1c216a34515ad3e4639

Feel free to create a pull request to absorb changes.

**Comment by afonsoguerra** [comment]
Thanks for this.
All merged now!
